home:
  moved: "&6Dein Zuhause wurde erfolgreich nach: %home% verschoben."

afk:
  events:
    onPlayerMove: true # Aktualisiert den Status, sobald der Spieler sich bewegt.
    onPlayerInteract: true # Aktualisiert den Status, sobald der Spieler mit Türen, TNT usw. interagiert.
    onPlayerChat: true # Aktualisiert den Status, sobald der Spieler chattet.
    onPlayerCommand: true # Aktualisiert den Status, sobald der Spieler Befehle ausführt.
    onPlayerBreak: false # Aktualisiert den Status, sobald Blöcke zerstört werden.
    onPlayerPlace: false # Aktualisiert den Status, sobald Blöcke platziert werden.

openid:
  messages:
    header: "&7&l&m----------&7&l[ OpenTopia &7&l]&m----------"
    minecraft-id: "&7Minecraft-ID: &f%id%"
    id: "&7ID: &f%id%"
    notify: "&fKlicke auf die ID, um sie zu kopieren."
    footer: "&7&l&m----------&7&l[ OpenTopia &7&l]&m----------"
    hover: "&6Klicke hier, um diese ID zu verwenden."
    signclick: "&6Klicke jetzt mit der linken Maustaste auf das Schild."
    signlate: "&cDer Vorgang wurde abgebrochen."
    signregister: "&aDas Schild wurde erfolgreich aktualisiert."
    nopermission: "&cDu hast keine Berechtigung dafür."
    noitems: "&cEntschuldigung, ich konnte die Items nicht finden. Bitte versuche es erneut."
    noItemInHand: "&cHalte ein Item in der Hand oder nutze /pipeid <Materialname>."

  sign:
    timeout: 5 # Timeout in Sekunden.
  permission: "Opentopia.pipeID"
